version: '3'
services:
  recommendarr:
    image: tannermiddleton/recommendarr:latest
    container_name: recommendarr
    ports:
      - "0.0.0.0:3030:80"
      - "0.0.0.0:3050:3050"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
    volumes:
      - ./server/data:/app/server/data
    restart: unless-stopped