version: '3'
services:
  recommendarr:
    image: tannermiddleton/recommendarr:latest
    container_name: recommendarr
    depends_on:
      - api
    ports:
      - "3030:80"
    restart: unless-stopped

  api:
    image: tannermiddleton/recommendarr-api:latest
    container_name: recommendarr-api
    ports:
      - "3050:3050"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
    volumes:
      - ./server/data:/app/server/data
    restart: unless-stopped