version: '3'
services:
  recommendarr:
    build: .
    container_name: recommendarr
    ports:
      - "3030:80"
      - "3050:3050"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
    volumes:
      - ./server/data:/app/server/data
    restart: unless-stopped