name: Docker Build and Push

on:
    push:
      branches:
        - main

jobs:
  build_and_push_images:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Check out repository code 🛎️
        uses: actions/checkout@v4

      - name: Get package version
        id: package_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx 🚀
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub 🚢
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and push UI image 🏗️
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME}}/recommendarr:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME}}/recommendarr:v${{ steps.package_version.outputs.VERSION }}
            ${{ secrets.DOCKER_HUB_USERNAME}}/recommendarr:latest
            
      - name: Build and push API server image 🏗️
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/api.Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME}}/recommendarr-api:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME}}/recommendarr-api:v${{ steps.package_version.outputs.VERSION }}
            ${{ secrets.DOCKER_HUB_USERNAME}}/recommendarr-api:latest